### ISSUE TITLE
希望增加规范缘由

### ISSUE THREAD

**Issue by shellphon** [hzlzh/Front-End-Standards#2]
规范看着好赞，有些明白缘由，有些不明其所以然，如果能加上规范的设计缘由，会更好吧。个人拙见

**Comment by hzlzh** [comment]
规范的细节点比较多，建议是逐条在自己的组内进行推敲，如果有不能接受的点翻阅资料技能查到原因，可以和组员 PK 得到结果，毕竟规范也是给大家一起来用的，必须要经得住众人之口。
