### ISSUE TITLE
mistake

### ISSUE THREAD

**Issue by iFiring** [hzlzh/Front-End-Standards#3]
2.4.1 JS 文件结构

---/js/
|---- /libs/plugin-1/       使用到的js插件1  
|---- /libs/plugin-2/       使用到的js插件2  
|---- /libs/plugin-3/       使用到的js插件3  
|---- script.js             单独书写的js  
|---- plugins.js            调用的plugins汇总  
## |---- **juqery**-1.9.x.min.js   调用jq库文件

**Comment by hzlzh** [comment]
多谢反馈，已修复 typo
https://github.com/hzlzh/Front-End-Standards/blob/gh-pages/index.html
